import io.micronaut.build.internal.generator.BeanGeneratorTask

plugins {
    id("java-library")
    id("groovy")
    id("io.micronaut.build.internal.test-suite-generator-java")
}

dependencies {
    testImplementation(mnValidation.validation)
    testImplementation(projects.micronautJsonSchemaAnnotations)
    testImplementation(mnSerde.micronaut.serde.jackson)
    testImplementation(projects.micronautJsonSchemaUtils)

    testAnnotationProcessor(projects.micronautJsonSchemaProcessor)
    testAnnotationProcessor(mnSerde.micronaut.serde.processor)
    testAnnotationProcessor(mn.micronaut.inject.java)

    testImplementation(mn.jackson.databind)

    testImplementation(mn.micronaut.http.server.netty)
    testImplementation(mn.micronaut.http.client)
    testImplementation(projects.micronautJsonSchemaValidation)
    testImplementation(mn.micronaut.inject.kotlin.test)
    testImplementation(mn.micronaut.inject.groovy.test)
    testImplementation(mn.micronaut.inject.java.test)
    testImplementation(mn.micronaut.inject)

    testImplementation(mnTest.micronaut.test.spock)
    testImplementation(mnTest.micronaut.test.junit5)
    testImplementation(mnTest.junit.jupiter.api)
    testRuntimeOnly(mnTest.junit.jupiter.engine)
    testImplementation(mnTest.junit.jupiter.params)
    testRuntimeOnly(mnTest.junit.platform.launcher)
}

def userGenerator = tasks.register("generateUser", BeanGeneratorTask) {
    language = "java"
    classpath.from(configurations.beanGenerator)
    jsonFile.convention(layout.projectDirectory.file("src/test/resources/user.schema.json"))
    outputDirectory.convention(layout.buildDirectory.dir("generated/jsonSchema"))
    packageName.convention("io.micronaut.jsonschema.generator.user")
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.add("-Amicronaut.jsonschema.baseUri=https://example.com/schemas")
}

tasks.named("generateUser") {
}

test {
    useJUnitPlatform()
}

sourceSets {
    test {
        java.srcDir(userGenerator.map(BeanGeneratorTask::getGeneratedSourcesDirectory))
    }
}
